---
title: "Final Project Proposal"
author: "Kayla Conley"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Final Project Proposal

Answering the questions in this document are worth 20 points for Question 5 in Week 9's Assignment.

## Where to Find Data

**If you have your own data from a research project, use it!**

If you don't have your own data, here are some suggestions for where to find data:

1.  From your lab group

If you are working in a lab group, you can almost certainly find data to work with from your lab! Ask your PI or other lab members if you can use their data for this project. It is often helpful to have data that relates somewhat to a project or topic you are familiar with.

2.  From me (actually from the National Phenology Network)!

I currently have a project helping the National Phenology Network take data collected by communitiy members and cleaning it up so it can be integrated into the NPN database.

If you choose to work with one of these datasets, I can give you some guidance on what the end product should look like.

You can find a list of the dataset options [here](https://archive.usanpn.org/results/dataset-list).

3.  From the "Data is Plural" Archive

[Data is Plural](https://www.data-is-plural.com/) is a weekly newsletter about complied datasets that people have found. They have an archive of all of the datasets that have been included in the newsletters, which is nearly 2000.

Just because the datasets have been compiled does not mean that they are clean! I've used a few of them in class as demonstrations.

4.  From an agency, NGO, or non-profit

If you have contacts in a local, state, or federal agency or non-profit, they likely have some languishing data floating around that you can clean up.

5.  A data repository

There are many data repositories where you can find data. I would recommend sticking to some of the other options above to keep your search a bit more constrained, but feel free to ultimately use any dataset you find that you would like to use.

## Project Guidelines

As a reminder, the general guidelines for the final project that the project will need to include core concepts covered in a certain number of weeks (6 for WFSC 496B, 10 for WFSC 596B), bringing together many aspects of what we will have learned through the course of the semester.

The final project for this course is worth 300 points (WFSC 496B) or 500 points (WFSC 596B).

## Questions

The following answers are not binding! You can change your final project as much as you'd like from what you propose here.

Answering these questions is meant to get you thinking about what data you would like to use and what tasks you might perform with the data.

Note: Your data set does not need to be ecological in nature if you have another interest. It should also not be a dataset that we have used in class (see me if you have questions).

1.  What data are you planning to use for the final project? Describe the data: its contents, its format(s), one or more dataframes, etc. If you have a link to the dataset, please include it. If you have a file that you can upload, please add it to the assignment submission.

    I plan in using a the Spring Tree Phenology Observation dataset the National Phenology Network.

    <https://archive.usanpn.org/node/35043>

2.  Does this data need to be cleaned in any way to make it tidy? If so, what needs to occur?

    Yes, the data needs to be cleaned. The data is in a wide format currently and I think it would be better in a long format. There are several areas in the excel sheet where cells are highlighted and there are several columns filled with "-99" that may need to be NA values.

3.  Speaking generally, what tasks will you perform with this dataset? It might include tasks that we have not yet covered how to accomplish in class, but come up with a general plan that you would like to follow.

    I will need to create a columns for the species name, site ID, and the phenological level. We might need to get rid of the highlighted cells if there is not metadata that explains why they are highlighted. The data also has multiple sheets so that will need to be condensed.

4.  One of the requirements of the final project is to make some type of plot using `ggplot2` with the data. What do you plan to plot from your data?

    I plan to plot the phenological level and the day of year. I can also create a plot for each species.

# Reflection

This reflection is worth 25 points, separate from your Week 9 assignment. Reflections are graded for completion only.

Write about 5 sentences addressing *at least* one of the following questions.

-   What has worked well for you in this course for you so far?
-   What has been particularly challenging for you so far?
-   Is there anything that I can do to help your learning in the course?
-   Other reflections about the content of the module that you would like to share.

*Answer*:

## Submitting this File

1.  Create a new repository in the class GitHub organization for your final project. Use the naming convention "LastName_FinalProject"
2.  Connect the repository to an RStudio project
3.  Create a series of appropriate sub-directories in your RStudio Project, including a `documents` folder.
4.  Move this file to the documents folder.
5.  Stage, commit, and push this document (and sub-directory) to GitHub with a descriptive commit message.
